apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: YOURNAME.DOMAIN
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-internal: "True"
    service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: CERTIFICATE_ARN
spec:
  ports:
  - port: 443
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer