apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-volume
          mountPath: /myvol/
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: nginx-claim